/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/optimized.glb 
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-astronaut-in-space-suit-loop-137d62cd820a4a6eba75304a11fb6f81
Title: Animated Astronaut in Space Suit Loop
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/optimized.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material0} skeleton={nodes.Object_102.skeleton} scale={0.013} />
        <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.material0} skeleton={nodes.Object_103.skeleton} scale={0.013} />
        <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material1} skeleton={nodes.Object_106.skeleton} scale={0.013} />
        <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.material2} skeleton={nodes.Object_109.skeleton} scale={0.013} />
      </group>
    </group>
  )
}

useGLTF.preload('/optimized.glb')
